data:
  data_dir: "data"
  save_dir: "results"
  url: "http://www.cs.cornell.edu/~cristian/data/cornell_movie_dialogs_corpus.zip"
  archive_name: "cornell_movie_dialogs_corpus.zip"
  corpus_name: "cornell movie-dialogs corpus"
  lines_file: "movie_lines.txt"
  conversations_file: "movie_conversations.txt"
  formated_file: "formatted_movie_lines.txt"

vocabulary:
  pad_token: 0
  sos_token: 1
  eos_token: 2
  max_length: 10
  min_count_to_trim: 3

training:
  epochs: 4000
  encoder_learning_rate: 0.0001
  decoder_learning_rate: 0.0005
  clip: 50.0
  teacher_forcing_ratio: 1.0
  batch_size: 128
  hidden_size: 500
  attention_method: "general"
  encoder_gru_layers: 2
  decoder_gru_layers: 2
  dropout_ratio: 0.1
  log_freq: 1
  save_freq: 500






